### ISSUE TITLE
까리뽕쌈 테마 찾기

### ISSUE THREAD

**Issue by gaonK** [gaonK/gaonK.github.io#1]
#### 까리뽕쌈 테마 찾기
- 어떤 테마를 써야 개발 이야기를 잘 쓸 수 있을까?
- 대중적인 Jekyll 쓸 것인가? 요샌 딴 것도 쓰더라공
- 일단 예뻤으면 좋겠음. ⚡️
- 카테고리화가 된다면 Best! (이러니 네이버, 티스토리를 못 벗어나고 있다.)
- 정 안 되면 괜찮은 태그 기능!

**Comment by JeaSungLEE** [comment]
찾으면 나도 알려줘
\

**Comment by gaonK** [comment]
@JeaSungLEE 결국 누추한 이 곳까지 찾아내셨네염. 까리뽕쌈 테마 찾으면 리스트업하겠음ㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by LenKIM** [comment]
잘 만들면 나도 알려줘- 이제 슬슬 블로그로 내용 옮겨야지-
기대된당

**Comment by gaonK** [comment]
@LenKIM ㅋㅋㅋㅋ 오빠... 내가 만들진 않을걸...? ㅋㅋㅋㅋ

**Comment by eastroots92** [comment]
퍼가요~❤️

**Comment by gaonK** [comment]
@JeaSungLEE 내가 할 일을,,,

**Comment by JeaSungLEE** [comment]
http://jekyllthemes.org
